export interface EmailTemplateParams {
  title: string;
  badge: string;
  heading: string;
  description: string;
  summaryRows: { label: string; value: string }[];
  confidentialNotice: string;
}

export function buildBrandedEmailHtml(params: EmailTemplateParams): string {
  const summaryRowsHtml = params.summaryRows
    .map(
      (row) => `
        <div style="display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #edf2f7; font-size: 14px;">
          <span style="color: #64748b; font-weight: 500;">${row.label}:</span>
          <span style="color: #0f172a; font-weight: 600;">${row.value}</span>
        </div>
      `,
    )
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f8fafc; margin: 0; padding: 24px; color: #1e293b;">
  <div style="max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; border: 1px solid #e2e8f0; box-shadow: 0 4px 12px rgba(0,0,0,0.03);">
    <div style="background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); padding: 32px 24px; text-align: center;">
      <h1 style="color: #ffffff; font-size: 24px; font-weight: 800; letter-spacing: -0.5px; margin: 0;">FinKing Operations</h1>
      <span style="display: inline-block; background: #0284c7; color: #ffffff; font-size: 11px; font-weight: 700; text-transform: uppercase; padding: 4px 8px; border-radius: 4px; margin-top: 8px;">
        ${params.badge}
      </span>
    </div>
    <div style="padding: 32px 24px;">
      <h2 style="font-size: 18px; font-weight: 700; color: #0f172a; margin-top: 0; margin-bottom: 12px;">${params.heading}</h2>
      <p style="font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 24px;">${params.description}</p>
      
      <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 18px; margin-bottom: 24px;">
        ${summaryRowsHtml}
      </div>

      <div style="font-size: 12px; line-height: 1.5; color: #64748b; background: #eff6ff; border-left: 3px solid #0284c7; padding: 12px; border-radius: 0 4px 4px 0; margin-bottom: 24px;">
        <strong>Notice:</strong> ${params.confidentialNotice}
      </div>
    </div>
    <div style="background: #f1f5f9; padding: 16px 24px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0;">
      &copy; 2026 FinKing Platform. Automated report generated by BullMQ queue worker.
    </div>
  </div>
</body>
</html>
  `;
}
